"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os, sys
import boto3

# SSM 클라이언트 생성
ssm = boto3.client('ssm', region_name='ap-northeast-2')  # 리전을 적절히 변경하세요

def get_parameter(parameter_name, isDecrypt=False):
    try:
        response = ssm.get_parameter(
            Name=parameter_name,
            WithDecryption=isDecrypt  # SecureString 타입의 경우 암호화 해제
        )
        return response['Parameter']['Value']
    except Exception as e:
        print(f"파라미터 조회 실패: {e}")
        return None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APPS_DIR = os.path.join(BASE_DIR, 'apps')
sys.path.insert(0, APPS_DIR)

DEBUG = get_parameter("/TrendAnalysis/adminDBSite/prod/DEBUG") 
SECRET_KEY = get_parameter("/TrendAnalysis/adminDBSite/prod/SECRET_KEY",True)
DATABASE_URI = get_parameter("/TrendAnalysis/adminDBSite/prod/DATABASE_URI",True)
DB_ID =get_parameter("/TrendAnalysis/adminDBSite/prod/DB_ID",True)
DB_PASSWORD = get_parameter("/TrendAnalysis/adminDBSite/prod/DB_PASSWORD",True)
DB_NAMES = [get_parameter("/TrendAnalysis/adminDBSite/prod/DB1_NAME"), get_parameter("/TrendAnalysis/adminDBSite/prod/DB2_NAME")]
MEDIA_PATH = os.path.join(BASE_DIR,get_parameter("/TrendAnalysis/adminDBSite/prod/MEDIA_PATH"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

ALLOWED_HOSTS = [".ap-northeast-2.compute.amazonaws.com",
                 ".sunnydb.site"
                 ]

# Application definition

INSTALLED_APPS = [
    'main.apps.MainConfig',
    'contentAdmin.apps.ContentAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    #BASE_DIR / 'static',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATIC_ROOT = '/srv/adminDBSite/static/'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/selectDB'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'  # 세션 쿠키의 이름
SESSION_COOKIE_AGE = 1209600       # 세션 쿠키의 유지 시간 (초 단위, 기본값: 2주, 1209600초)
SESSION_SAVE_EVERY_REQUEST = True  # 모든 요청 시 세션 저장
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 브라우저가 닫히면 세션을 유지할지 여부
